repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        additional_dependencies:
          - black
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        additional_dependencies:
          - flake8
